version: '3.3'

services:

  app:
    build: .
    container_name: 'app'
    ports:
      - 5000:5000
    env_file:
      - ./.env
    environment:
      FAST_API_PORT: ${FAST_API_PORT}
    stdin_open: true
    tty: true
    volumes:
      - .:/app